name: docker-github-actions
on:
  workflow_dispatch:

jobs:
   my_job:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.4
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
    steps:
#         - name: check node version
#           run: node -v
        - name: check python version
          run: python --version
