name: learn-github-actions
on:
  workflow_dispatch:

jobs:
   my_job:
   runs-on: ubuntu-latest
   container:
    image: node:14.16
    env:
      NODE_ENV: development
    ports:
      - 80
    volumes:
      - my_docker_volume:/
    steps:
        - name: check node version
          run: node -v
