name: docker-github-actions
on:
  workflow_dispatch: null
jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: 'python:3.10.4'
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - 'my_docker_volume:/volume_mount'
    steps:
      - name: check python version
        run: python --version
  runner_job:
    runs-on: ubuntu-latest
    steps:
      - name: check python version in runner
        run: python --version
