name: learn-github-actions
on:
#   push:
#     branches:
#     - main
#     paths-ignore:
#     - 'script.py'
  workflow_dispatch:
  #pull_request:
    #branches:
    #- main  

  #schedule:
    #- cron: '*/1 * * * *'  

jobs:
  check-python-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: python version
        run: python --version
