name: learn-github-actions
on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
    - 'README.md'
jobs:
  check-python-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo
        run: echo Hello world!
