name: learn-github-actions
on: [workflow_dispatch]
jobs:
  check-python-version:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          node-version: '3.6'
      - run: python --version