name: 'Create SNS topic'
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:  
  sns_topics:
    name: 'create sns topic'
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CSSP_AWS_GITHUB_030462125157_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CSSP_AWS_GITHUB_030462125157_PROD_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create SNS topic
      id: sns_topic_arn1
      run:  |
        topic_arn=$(aws sns create-topic --name cssp-idle-resource-sns-topic  -output text)
        echo "::set-output name=topic_arn::$topic_arn"

    - name: Subscribe to SNS topic
      run:  echo ${{ steps.sns_topic_arn.outputs.topic_arn }}
