name: 'Create SNS topic'
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:  
  sns_topics:
    name: 'create sns topic'
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CSSP_AWS_GITHUB_030462125157_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CSSP_AWS_GITHUB_030462125157_PROD_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create SNS topic
      id: sns_topic_arn
      run:  |
        topic_arn=$(aws sns create-topic --name cssp-idle-resource-sns-topic --output text)
        echo "Arn: $topic_arn"
        echo "::set-output name=topic_arn::$topic_arn"

    - name: Subscribe to SNS topic
      run:  |
        echo ${{ steps.sns_topic_arn.outputs.topic_arn }}
        
        aws sns subscribe \
        --topic-arn ${{ steps.sns_topic_arn.outputs.topic_arn }} \
        --protocol email \
        --notification-endpoint aakash.vishwakarma@cloudeq.com


        aws sns subscribe \
        --topic-arn ${{ steps.sns_topic_arn.outputs.topic_arn }} \
        --protocol email \
        --notification-endpoint abhishek.sharma@cloudeq.com
        
    - name: cloudwatch alarm
      run:  |
        aws cloudwatch put-metric-alarm \
        --alarm-name Error-alarm-cssp-idle-EBS-lambda \
        --alarm-description "Alarm when error occured in EBS lambda" \
        --metric-name Errors --namespace AWS/Lambda \
        --statistic Average --period 60 --threshold 0 \
        --comparison-operator GreaterThanThreshold  \
        --dimensions Name=FunctionName,Value=idle-resource-ebs-lambda-function \
        --statistic Sum --evaluation-periods 1 \
        --alarm-actions ${{ steps.sns_topic_arn.outputs.topic_arn }}

        aws cloudwatch put-metric-alarm \
        --alarm-name Error-alarm-cssp-idle-EIP-lambda \
        --alarm-description "Alarm when error occured in EBS lambda" \
        --metric-name Errors --namespace AWS/Lambda \
        --statistic Average --period 60 --threshold 0 \
        --comparison-operator GreaterThanThreshold  \
        --dimensions Name=FunctionName,Value=idle-resource-eip-lambda-function \
        --statistic Sum --evaluation-periods 1 \
        --alarm-actions ${{ steps.sns_topic_arn.outputs.topic_arn }}

  
