name: First Cron Job

       # Controls when the workflow will run
on:
  # Triggers the workflow every 1 minutes
  schedule:
    - cron: "*/5 * * * *"
    
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
#     runs-on: windows-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
#       - name: print present directory with linux
#         run: ifconfig
#         continue-on-error: true
        
#       - name: print present directory with windows
#         run: ipconfig
       

